### ISSUE TITLE
ProjectKeys.encode should accept Uint8Array instead of Buffer type

### ISSUE THREAD

**Issue by achou11** [digidem/mapeo-crypto#14]
Using the lowest common denominator makes it easier to use in the wild

Example of improved usage is here: https://github.com/digidem/mapeo-core-next/pull/199#discussion_r1301996191

**Comment by gmaclennan** [comment]
Hmm... actually not sure about this. The [sodium-native docs](https://sodium-friends.github.io/docs/docs/getstarted) say that all the methods accept buffers, and the tests are only run with buffers. It does seem that they will work with Uint8Arrays, and I think the holepunch libraries use them with Uint8array, but I don't think it's a good idea for us to risk it. I'm also not sure it makes sense to convert to a buffer in this library, so I would actually stick with doing `Buffer.from(myUint8Array)` when calling this function.
